#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yarn
Version  : 1.12.3
Release  : 11
URL      : https://github.com/yarnpkg/yarn/releases/download/v1.12.3/yarn-v1.12.3.tar.gz
Source0  : https://github.com/yarnpkg/yarn/releases/download/v1.12.3/yarn-v1.12.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: yarn-bin = %{version}-%{release}
Requires: yarn-data = %{version}-%{release}
Requires: yarn-license = %{version}-%{release}
Requires: nodejs
Patch1: build.patch

%description
<p align="center">
<a href="https://yarnpkg.com/">
<img alt="Yarn" src="https://github.com/yarnpkg/assets/blob/master/yarn-kitten-full.png?raw=true" width="546">
</a>
</p>

%package bin
Summary: bin components for the yarn package.
Group: Binaries
Requires: yarn-data = %{version}-%{release}
Requires: yarn-license = %{version}-%{release}

%description bin
bin components for the yarn package.


%package data
Summary: data components for the yarn package.
Group: Data

%description data
data components for the yarn package.


%package doc
Summary: doc components for the yarn package.
Group: Documentation

%description doc
doc components for the yarn package.


%package license
Summary: license components for the yarn package.
Group: Default

%description license
license components for the yarn package.


%prep
%setup -q -n yarn-v1.12.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541633907
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541633907
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/yarn
cp LICENSE %{buildroot}/usr/share/package-licenses/yarn/LICENSE
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/node_modules/yarn/LICENSE
/usr/lib/node_modules/yarn/Makefile
/usr/lib/node_modules/yarn/README.md
/usr/lib/node_modules/yarn/bin/yarn
/usr/lib/node_modules/yarn/bin/yarn.cmd
/usr/lib/node_modules/yarn/bin/yarn.js
/usr/lib/node_modules/yarn/bin/yarnpkg
/usr/lib/node_modules/yarn/bin/yarnpkg.cmd
/usr/lib/node_modules/yarn/lib/cli.js
/usr/lib/node_modules/yarn/lib/v8-compile-cache.js
/usr/lib/node_modules/yarn/package.json

%files bin
%defattr(-,root,root,-)
/usr/bin/yarnpkg

%files data
%defattr(-,root,root,-)
/usr/share/licenses/kgname/LICENSE

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/kgname/README.md

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/yarn/LICENSE
